---
Name: sunnysideup-config-checks
Before:
    - '*'
---
SilverStripe\Control\Director:
  rules:
    admin/checkconfigsforsite//$Action/$ID/$OtherID: Sunnysideup\ConfigManager\Control\CheckConfigsController
